apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-credentials
  namespace: monitoring
type: Opaque
data:
  smtp-from: YmliZWtrODUzQGdtYWlsLmNvbQ==
  smtp-username: YmliZWtrODUzQGdtYWlsLmNvbQ==
  smtp-password: dXBpeCBvbHBxIHBibHQgbWNqcA==
  email-to: YXZpanVudGhhcGdhN0BnbWFpbC5jb20=
  slack-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDBBOVEySkQwNTYvQjBBOVEyRERNNlUveVdCeExPOGtRdlczSTB0dWk4bXhGT2Fz
